version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/nest

volumes:
  mongodb-data:
